#!/usr/bin/env Rscript

library(tdmsreader)
library(futile.logger)

flog.threshold(DEBUG)

### Program

options = commandArgs(trailingOnly = TRUE)
if (length(options) < 1) {
    stop("Usage: tdmsindex <file> <output>")
}

# open file
my_file = file(options[1], "rb")
print(TdmsFile)
print(TdmsIndexFile)

main <- TdmsIndexFile$new(my_file)

for(elt in ls(main$objects)) {
    r = main$objects[[elt]]
    if(r$has_data) {
        t = r$time_track()
        s = r$data
        flog.debug('datalen %d', length(s))
        png(options[2],width=5000,height=600)
        plot(t[1:100000],s[1:100000], type='l')
        dev.off()
    }
}

close(my_file)
