#!/usr/bin/env Rscript

library(tdmsreader)
library(futile.logger)

flog.threshold(DEBUG)

### Program

options = commandArgs(trailingOnly = TRUE)
if (length(options) < 1) {
    stop('Usage: tdmsreader <file> <output>')
}

# open file
my_file = file(options[1], 'rb')
index_file = file(paste0(options[1], '_index'), 'rb')

start = 0.04
end = 0.08
main = TdmsFile$new(my_file)
main$read_data(my_file, start, end)

for (elt in ls(main$objects)) {
    r = main$objects[[elt]]
    if (r$has_data) {
        print(elt)
        t = r$time_track(start, end)
        s = r$data
        flog.debug('datalen %d', length(s))
        png(options[2], width=5000, height=600)
        plot(t,s, type='l')
        dev.off()
    }
}

close(my_file)
close(index_file)
